In [1]:
import pandas as pd
import numpy as np
import sklearn as SL
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn import metrics
import matplotlib.pyplot as plt
df = pd.read_csv('C:\\Users\\monam\\OneDrive\\Desktop\\testt2.csv')
df.head()

EXP_1  EXP_2  IMP_1  IMP_2  RES_1  RES_2  RES_3  RES_4  FOOBE_1  FOOBE_2  \
0      5      5      7      6      2      3      6      6        6        7   
1      5      5      6      5      5      2      3      3        7        6   
2      5      5      5      5      5      3      4      5        6        6   
3      7      7      7      7      7      1      5      3        7        7   
4      5      5      5      4      5      3      4      4        4        7   

   ...  TRU_5  AGE  GEN  DIS  ETH  EDU  CWS  CHI  HHI  TR1  
0  ...      3    1    1    2    1    4    1    2    8    4  
1  ...      3    6    1    2    1    5    6    1    6    5  
2  ...      4    6    1    2    1    4    6    1    3    5  
3  ...      4    2    2    3    1    5    3    2    4    2  
4  ...      1    4    1    1    1    4    2    1    4    5  

[5 rows x 60 columns]

In [3]:
X = df.iloc[:, 0:59].values
y = df.iloc[:, 59].values

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

NameError: name 'X_train' is not defined

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model_tree = DecisionTreeClassifier (max_leaf_nodes=8, class_weight= 'balanced' )
model_tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', max_leaf_nodes=8)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

NameError: name 'y_pred' is not defined

In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train, y_train)
y_pred= classifier.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 14   1   1   0   8]
 [  7   1   0   0  12]
 [  1   1   0   0  16]
 [  3   0   0   0   8]
 [  7   2   0   0 128]]
              precision    recall  f1-score   support

           1       0.44      0.58      0.50        24
           2       0.20      0.05      0.08        20
           3       0.00      0.00      0.00        18
           4       0.00      0.00      0.00        11
           5       0.74      0.93      0.83       137

    accuracy                           0.68       210
   macro avg       0.28      0.31      0.28       210
weighted avg       0.55      0.68      0.61       210

0.680952380952381


C:\Users\monam\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\monam\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\monam\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
from imblearn.over_sampling import SMOTE

# Apply SMOTE to balance the classes
smote = SMOTE(sampling_strategy='auto', random_state=0)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Train the model on the resampled data
classifier.fit(X_train_resampled, y_train_resampled)

RandomForestClassifier(random_state=0)

In [13]:
from imblearn.over_sampling import SMOTE

# Apply SMOTE to balance the classes
smote = SMOTE(sampling_strategy='auto', random_state=0)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Train the model on the resampled data
classifier.fit(X_train_resampled, y_train_resampled)
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 15   1   3   0   5]
 [  5   6   1   1   7]
 [  2   6   4   0   6]
 [  4   2   0   2   3]
 [  8  10   9   4 106]]
              precision    recall  f1-score   support

           1       0.44      0.62      0.52        24
           2       0.24      0.30      0.27        20
           3       0.24      0.22      0.23        18
           4       0.29      0.18      0.22        11
           5       0.83      0.77      0.80       137

    accuracy                           0.63       210
   macro avg       0.41      0.42      0.41       210
weighted avg       0.65      0.63      0.64       210

0.6333333333333333
